name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Use the "postgres" hostname to point to the service container
      DB_SOURCE: "postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable"
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h postgres -p 5432 -U root; do
            sleep 1;
          done
        env:
          PGPASSWORD: secret

      - name: Run migrations
        run: migrate -path db/migration -database "$DB_SOURCE" -verbose up  

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
